import { useState } from 'react'
import { FiBarChart2, FiDownload, FiPrinter } from 'react-icons/fi'
import { buildAlerts } from '../data/portalAlerts.js'
import { usePortalData } from '../data/usePortalData.js'
import { toArray } from '../utils/arrayUtils.js'
import './Reports.css'

const reportMap = { 'Production Report': 'production', 'QC Report': 'qc', 'Inventory Report': 'inventory', 'Failed Batch Report': 'qc', 'Laboratory Report': 'laboratory', 'Customer Report': 'customers', 'Customer Requirement Report': 'requirements' }
const csvEscape = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`

function Reports() {
  const { records } = usePortalData()
  const [report, setReport] = useState('Production Report')
  const [filters, setFilters] = useState({ from: '', to: '', customer: '', product: '', status: 'All statuses' })
  const [notice, setNotice] = useState('')
  const data = report === 'Alert Report' ? buildAlerts(records) : toArray(records[reportMap[report]])
  const rows = data.filter((record) => (!filters.from || (record.date || record.testDate || record.updated || record.created) >= filters.from) && (!filters.to || (record.date || record.testDate || record.updated || record.created) <= filters.to) && (!filters.customer || `${record.customer || record.company}`.toLowerCase().includes(filters.customer.toLowerCase())) && (!filters.product || String(record.product || '').toLowerCase().includes(filters.product.toLowerCase())) && (filters.status === 'All statuses' || record.status === filters.status || record.result === filters.status))
  const update = (key) => (event) => setFilters((current) => ({ ...current, [key]: event.target.value }))
  const generate = (event) => { event.preventDefault(); setNotice(`${report} generated with ${rows.length} matching records.`) }
  const exportCsv = () => { const columns = [...new Set(rows.flatMap((row) => Object.keys(row)))]; const csv = [columns.join(','), ...rows.map((row) => columns.map((column) => csvEscape(row[column])).join(','))].join('\n'); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${report.toLowerCase().replaceAll(' ', '-')}.csv`; link.click(); URL.revokeObjectURL(url); setNotice(`${rows.length} records exported to CSV.`) }
  return <div className="reports-page"><header className="reports-header"><div><h1>Reports</h1><p>Generate operational reports from current production, QC, inventory and customer data.</p></div><FiBarChart2 /></header>{notice && <div className="data-notice" role="status">{notice}</div>}<section className="reports-panel"><form className="report-form" onSubmit={generate}><label><span>Report Type</span><select value={report} onChange={(event) => setReport(event.target.value)}>{[...Object.keys(reportMap), 'Alert Report'].map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Date From</span><input type="date" value={filters.from} onChange={update('from')} /></label><label><span>Date To</span><input type="date" value={filters.to} onChange={update('to')} /></label><label><span>Customer</span><input placeholder="All customers" value={filters.customer} onChange={update('customer')} /></label><label><span>Product</span><input placeholder="All products" value={filters.product} onChange={update('product')} /></label><label><span>Status</span><select value={filters.status} onChange={update('status')}><option>All statuses</option><option>Active</option><option>Completed</option><option>Pending</option><option>PENDING</option><option>PASS</option><option>FAIL</option><option>Failed</option><option>Open</option><option>Resolved</option></select></label><div className="report-actions"><button className="btn btn-primary"><FiBarChart2 /> Generate Report</button><button type="button" className="btn btn-secondary" onClick={exportCsv}><FiDownload /> Export CSV</button><button type="button" className="btn btn-secondary" onClick={() => window.print()}><FiPrinter /> Print</button></div></form></section><section className="reports-panel report-results"><div className="panel-header"><FiBarChart2 className="panel-header-icon" /><h2>{report} Preview <span>({rows.length} records)</span></h2></div>{rows.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr>{Object.keys(rows[0]).map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.slice(0, 10).map((row, index) => <tr key={`${row.id || 'row'}-${index}`}>{Object.keys(rows[0]).map((column) => <td key={column}>{row[column] || '—'}</td>)}</tr>)}</tbody></table></div> : <p className="empty-state">No records match the selected filters.</p>}</section></div>
}
export default Reports
