import mongoose from 'mongoose'

const { Schema } = mongoose
const common = { timestamps: true, versionKey: false }
const status = { type: String, trim: true, default: 'Active' }

export const Customer = mongoose.model('Customer', new Schema({ customerId: { type: String, required: true, unique: true, trim: true }, companyName: { type: String, required: true, trim: true }, contactPerson: String, phone: String, email: String, address: String, product: String, specification: String, application: String, status }, common))
export const Product = mongoose.model('Product', new Schema({ productId: { type: String, required: true, unique: true, trim: true }, name: { type: String, required: true, trim: true }, category: String, description: String, application: String, unit: String, status }, common))
export const Formulation = mongoose.model('Formulation', new Schema({ formulationId: { type: String, required: true, unique: true, trim: true }, product: { type: String, required: true }, customer: String, version: String, rawMaterials: String, targetSpecification: String, application: String, status }, common))
export const Production = mongoose.model('Production', new Schema({ productionId: { type: String, required: true, unique: true, trim: true }, date: { type: Date, required: true }, product: String, customer: String, batchNumber: { type: String, required: true }, plannedQuantity: String, producedQuantity: String, operator: String, status: { ...status, default: 'Planned' }, remarks: String }, common))
export const QCRecord = mongoose.model('QCRecord', new Schema({ qcId: { type: String, required: true, unique: true, trim: true }, batchNumber: { type: String, required: true }, product: String, customer: String, sampleDate: Date, testDate: Date, testedBy: String, parameters: { type: Schema.Types.Mixed, default: {} }, result: { type: String, enum: ['PENDING', 'PASS', 'FAIL'], default: 'PENDING' }, remarks: String }, common))
export const LabTest = mongoose.model('LabTest', new Schema({ sampleId: { type: String, required: true, unique: true, trim: true }, batchNumber: String, customer: String, product: String, labLocation: String, testParameter: String, reading: String, unit: String, specification: String, testDate: Date, analyst: String, result: { type: String, enum: ['PENDING', 'PASS', 'FAIL'], default: 'PENDING' }, remarks: String }, common))
export const Inventory = mongoose.model('Inventory', new Schema({ itemId: { type: String, required: true, unique: true, trim: true }, itemName: { type: String, required: true, trim: true }, category: String, currentStock: { type: Number, default: 0 }, minimumStock: { type: Number, default: 0 }, maximumStock: { type: Number, default: 0 }, unit: String, supplier: String }, common))
export const CustomerRequirement = mongoose.model('CustomerRequirement', new Schema({ requirementId: { type: String, required: true, unique: true, trim: true }, customer: String, product: String, specification: String, requestedQuantity: String, requiredParameters: String, dueDate: Date, assignedPerson: String, status: { ...status, default: 'New' }, remarks: String }, common))
export const Alert = mongoose.model('Alert', new Schema({ type: { type: String, required: true }, priority: { type: String, enum: ['High', 'Medium', 'Low'], default: 'Medium' }, description: { type: String, required: true }, relatedId: String, status: { type: String, enum: ['Open', 'Resolved'], default: 'Open' } }, common))
